#!/usr/bin/env node
// generate.js — parses all dated .md files and writes data.js
// Run: node generate.js

const fs   = require('fs');
const path = require('path');

const dir = __dirname;

const mdFiles = fs.readdirSync(dir)
  .filter(f => /^\d{4}-\d{2}-\d{2}.*\.md$/.test(f))
  .sort();

// ── helpers ──────────────────────────────────────────────────────────────────

function makeId(date, num, title) {
  const slug = title.toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-|-$/g, '')
    .slice(0, 28);
  return `${date}-${num}-${slug}`;
}

function cleanDescription(text) {
  return text
    .replace(/---\s*[\r\n]+Generated[\s\S]*/g, '')      // footer block
    .replace(/\*\*Research Insights?:\*\*[\s\S]*/gi, '') // research section
    .replace(/CNAME[\s\S]*/gi, '')                       // DNS junk
    .replace(/^Generated by[\s\S]*/m, '')                // inline footer
    .replace(/^---\s*$/gm, '')                           // hr lines
    .replace(/\n{3,}/g, '\n\n')
    .trim();
}

// Parse ideas from a block of text, assigning the given category
function parseIdeasFromBlock(text, category, date) {
  const ideas = [];

  // Try **Idea N: Title** (bold) first
  let boldMatches = [...text.matchAll(/\*\*Idea\s+(\d+):\s*(.*?)\*\*/g)];

  // Fallback: plain  Idea N: Title  (start of line)
  const plainMatches = boldMatches.length === 0
    ? [...text.matchAll(/^Idea\s+(\d+):\s+(.+)$/gm)]
    : [];

  const matches = boldMatches.length > 0 ? boldMatches : plainMatches;

  for (let i = 0; i < matches.length; i++) {
    const match  = matches[i];
    const num    = parseInt(match[1], 10);
    const title  = match[2]
      .replace(/🛠️\s*(DEV\s*TOOL)?/gi, '')
      .replace(/📱\s*(MOBILE\s*APP)?/gi, '')
      .trim();

    if (!title) continue;

    const startIdx = match.index + match[0].length;
    const endIdx   = i + 1 < matches.length ? matches[i + 1].index : text.length;
    const desc     = cleanDescription(text.slice(startIdx, endIdx));

    ideas.push({
      id:         makeId(date, num, title),
      date,
      category,   // 'general' | 'developer' | 'mobile'
      title,
      description: desc,
      ideaNumber: num,
      sourceFile: path.basename(date + '.md'), // overwritten below
    });
  }

  return ideas;
}

// ── file parser ───────────────────────────────────────────────────────────────

function parseFile(filename) {
  const content  = fs.readFileSync(path.join(dir, filename), 'utf8');
  const dateMatch = filename.match(/^(\d{4}-\d{2}-\d{2})/);
  const date      = dateMatch ? dateMatch[1] : 'unknown';

  const ideas = [];
  const hasGeneral = /^## General Ideas?/im.test(content);
  const hasDev     = /^## Developer Tools?/im.test(content);
  const hasMobile  = /^## Mobile (App )?Ideas?/im.test(content);

  if (hasGeneral || hasDev || hasMobile) {
    // Split content into category sections
    const lines = content.split('\n');
    let currentCat  = 'general';
    let sectionLines = [];

    const flush = () => {
      if (sectionLines.length === 0) return;
      const block = sectionLines.join('\n');
      const parsed = parseIdeasFromBlock(block, currentCat, date);
      parsed.forEach(i => { i.sourceFile = filename; });
      ideas.push(...parsed);
      sectionLines = [];
    };

    for (const line of lines) {
      if (/^## General/i.test(line))   { flush(); currentCat = 'general'; }
      else if (/^## Developer/i.test(line)) { flush(); currentCat = 'developer'; }
      else if (/^## Mobile/i.test(line)) { flush(); currentCat = 'mobile'; }
      else                              { sectionLines.push(line); }
    }
    flush();
  } else {
    // No section headers — all ideas treated as General
    const parsed = parseIdeasFromBlock(content, 'general', date);
    parsed.forEach(i => { i.sourceFile = filename; });
    ideas.push(...parsed);
  }

  return ideas;
}

// ── main ─────────────────────────────────────────────────────────────────────

const allIdeas = [];

for (const file of mdFiles) {
  try {
    const fileIdeas = parseFile(file);
    allIdeas.push(...fileIdeas);
    console.log(`✓  ${file.padEnd(32)}  ${fileIdeas.length} ideas`);
  } catch (e) {
    console.error(`✗  ${file}: ${e.message}`);
  }
}

// Deduplicate IDs
const seenIds = new Set();
for (const idea of allIdeas) {
  let id      = idea.id;
  let counter = 2;
  while (seenIds.has(id)) id = `${idea.id}-${counter++}`;
  idea.id = id;
  seenIds.add(id);
}

const meta = {
  processedFiles: mdFiles,
  generatedAt:    new Date().toISOString(),
  totalIdeas:     allIdeas.length,
  lastFileDate:   mdFiles.length
    ? (mdFiles[mdFiles.length - 1].match(/^(\d{4}-\d{2}-\d{2})/) || [])[1] || null
    : null,
};

const output = [
  `// Auto-generated by generate.js — do not edit manually`,
  `// Last generated: ${meta.generatedAt}`,
  `// Total: ${allIdeas.length} ideas from ${mdFiles.length} files`,
  `window.IDEAS_DATA = ${JSON.stringify(allIdeas, null, 2)};`,
  `window.IDEAS_META = ${JSON.stringify(meta, null, 2)};`,
].join('\n') + '\n';

fs.writeFileSync(path.join(dir, 'data.js'), output, 'utf8');

console.log(`\n✓  data.js written — ${allIdeas.length} ideas from ${mdFiles.length} files`);
